import { jsPDF } from "jspdf";
import type { SalaryAnalysis } from "./calculator";
import type { NegotiationPack } from "./negotiation";
import { formatCurrency, ordinal } from "./utils";

export function generatePdf(
  analysis: SalaryAnalysis,
  pack: NegotiationPack
): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  function addText(
    text: string,
    size: number,
    style: "normal" | "bold" = "normal",
    color: [number, number, number] = [245, 245, 247]
  ) {
    doc.setFontSize(size);
    doc.setFont("helvetica", style);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, contentWidth);
    const lineHeight = size * 0.5;
    for (const line of lines) {
      if (y > 270) {
        doc.addPage();
        y = margin;
      }
      doc.text(line, margin, y);
      y += lineHeight;
    }
  }

  function addSpace(mm: number) {
    y += mm;
    if (y > 270) {
      doc.addPage();
      y = margin;
    }
  }

  function addSeparator() {
    doc.setDrawColor(60, 60, 80);
    doc.line(margin, y, pageWidth - margin, y);
    y += 6;
  }

  // Background
  doc.setFillColor(10, 10, 15);
  doc.rect(0, 0, pageWidth, doc.internal.pageSize.getHeight(), "F");

  // Header
  addText("UnderChozen", 24, "bold", [124, 92, 252]);
  addText("Compensation Analysis Report", 11, "normal", [142, 142, 147]);
  addSpace(8);
  addSeparator();

  // Summary
  addText("Summary", 16, "bold");
  addSpace(3);
  addText(
    `Role: ${analysis.input.jobTitle} (${analysis.levelUsed})`,
    10,
    "normal",
    [180, 180, 185]
  );
  addText(
    `Location: ${analysis.input.city} | Industry: ${analysis.input.industry}`,
    10,
    "normal",
    [180, 180, 185]
  );
  addText(
    `Current Salary: ${formatCurrency(analysis.input.currentSalary)}`,
    10,
    "normal",
    [180, 180, 185]
  );
  addText(
    `Market Median: ${formatCurrency(analysis.marketMedian)}`,
    10,
    "normal",
    [180, 180, 185]
  );
  addText(
    `Market Range: ${formatCurrency(analysis.marketLow)} – ${formatCurrency(analysis.marketHigh)}`,
    10,
    "normal",
    [180, 180, 185]
  );
  addText(
    `Your Percentile: ${ordinal(analysis.percentile)}`,
    10,
    "normal",
    [180, 180, 185]
  );

  if (analysis.isUnderpaid) {
    addText(
      `Compensation Gap: -${formatCurrency(Math.abs(analysis.delta))}/year`,
      10,
      "bold",
      [255, 69, 58]
    );
    addText(
      `Lifetime Impact (10yr): ~${formatCurrency(analysis.lifetimeImpact)}`,
      10,
      "normal",
      [255, 69, 58]
    );
  }

  addSpace(6);
  addSeparator();

  // Raise Range
  addText("Recommended Raise Request", 16, "bold");
  addSpace(3);
  addText(
    `Conservative: ${formatCurrency(pack.raiseRange.low)}`,
    10,
    "normal",
    [180, 180, 185]
  );
  addText(
    `Target: ${formatCurrency(pack.raiseRange.target)}`,
    10,
    "bold",
    [124, 92, 252]
  );
  addText(
    `Stretch: ${formatCurrency(pack.raiseRange.high)}`,
    10,
    "normal",
    [180, 180, 185]
  );
  addSpace(6);
  addSeparator();

  // Email Script
  addText("Negotiation Email Script", 16, "bold");
  addSpace(3);
  addText(pack.emailScript, 9, "normal", [160, 160, 165]);
  addSpace(6);
  addSeparator();

  // Talking Points
  addText("Manager Meeting Talking Points", 16, "bold");
  addSpace(3);
  pack.talkingPoints.forEach((point, i) => {
    addText(`${i + 1}. ${point}`, 9, "normal", [160, 160, 165]);
    addSpace(2);
  });
  addSpace(4);
  addSeparator();

  // Objection Handling
  addText("Objection Handling Responses", 16, "bold");
  addSpace(3);
  pack.objectionHandling.forEach((item) => {
    addText(`"${item.objection}"`, 9, "bold", [255, 69, 58]);
    addText(item.response, 9, "normal", [160, 160, 165]);
    addSpace(4);
  });
  addSeparator();

  // If Denied
  addText("If Denied: Next Steps", 16, "bold");
  addSpace(3);
  pack.ifDeniedStrategy.forEach((step) => {
    addText(`• ${step}`, 9, "normal", [160, 160, 165]);
    addSpace(2);
  });
  addSpace(4);
  addSeparator();

  // 3-Year Model
  addText("3-Year Compensation Growth Model", 16, "bold");
  addSpace(3);
  pack.threeYearModel.forEach((row) => {
    addText(
      `Year ${row.year}: ${formatCurrency(row.projected)} (+${row.growth})`,
      10,
      "normal",
      [180, 180, 185]
    );
    addSpace(2);
  });
  addSpace(6);

  // Footer
  addText(
    "Market ranges based on aggregated public compensation data and cost-of-living adjustments.",
    7,
    "normal",
    [100, 100, 105]
  );
  addText("Generated by UnderChozen", 7, "normal", [100, 100, 105]);

  doc.save("UnderChozen-Compensation-Report.pdf");
}
